apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.12.1
  image: $REGISTRY/elasticsearch:7.12.1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false